export const QuestionnaireData = [
  {
    types: ['ethnicity', 'religion', 'beliefs'],
    ethnicity: {
      title: 'What’s your ethnicity?',
      visibility: false,
      singleSelection: true,
      options: [
        'Latino',
        'Middle Eastern',
        'Pacific Islander',
        'South Asian',
        'Southeast Asian',
        'White/Caucasian',
        'Other',
        'Perefer not to say',
      ],
    },
    religion: {
      singleSelection: true,
      title: 'What is your religion?',
      visibility: false,
      options: [
        'Hindu',
        'Jewish',
        'Muslim',
        'Catholic',
        'Spiritual',
        'Agnostic',
        'Atheist',
        'Buddhist',
        'Sikh',
        'Other',
        'Perefer not to say',
      ],
    },
    beliefs: {
      singleSelection: true,
      title: 'What are your political beliefs?',
      visibility: false,
      options: [
        'Liberal',
        'Moderate',
        'Conservative',
        'Not Political',
        'Other',
        'Perefer not to say',
      ],
    },
  },
  {
    types: [
      'relationship_status',
      'gender',
      'body_type',
      'sexual_orientation',
      'sexual_preference',
    ],
    relationship_status: {
      title: 'What is your relationship status?',
      visibility: false,
      singleSelection: true,
      options: [
        'Single',
        'In a Relationship',
        'Open Relationship',
        'Married',
        'Polyamorous Relationship',
        'Divorced',
        'Widowed',
      ],
    },
    gender: {
      title: 'What is your gender identity?',
      visibility: false,
      singleSelection: true,
      options: ['Man', 'Non-binary', 'Trans Man', 'Trans Woman'],
    },
    body_type: {
      title: 'What is your body type?',
      visibility: false,
      singleSelection: true,
      options: ['Slim', 'Toned', 'Average', 'Stocky', 'Muscular'],
    },
    sexual_orientation: {
      title: 'What is your sexual orientation?',
      visibility: false,
      singleSelection: true,
      options: ['Gay', 'Bisexual', 'Queer', 'Curious', 'Pansexual', 'Straight'],
    },
    sexual_preference: {
      title: 'What is your sexual preference?',
      visibility: false,
      singleSelection: true,
      options: [
        'Bottom',
        'Vers Bottom',
        'Versatile',
        'Vers Top',
        'Top',
        'Oral',
        'Fetish',
      ],
    },
  },
  {
    types: ['Interests'],
    Interests: {
      title: 'What is your interests?',
      singleSelection: false,
      icon_visibility: true,
      visibility: false,
      options: [
        'Acting',
        'Archery',
        'Art',
        'Brewing',
        'Board Games',
        'Breweries',
        'Computer Programming',
        'Chess',
        'Cooking',
        'Dance',
        'Digital Art',
        'Darts',
        'Drawing',
        'Film making',
        'Fitness',
        'Flying',
        'Gaming',
        'Gardening',
        'Guitar',
        'Investing',
        'InteriorDesign',
        'Kniting',
      ],
      optionImage: [
        require('@/assets/ic_interest/ic_acting/ic_acting.png'),
        require('@/assets/ic_interest/ic_archery/ic_archery.png'),
        require('@/assets/ic_interest/ic_art/ic_art.png'),
        require('@/assets/ic_interest/ic_brewing/ic_brewing.png'),
        require('@/assets/ic_interest/ic_boardgames/ic_boardgames.png'),
        require('@/assets/ic_interest/ic_breweries/ic_breweries.png'),
        require('@/assets/ic_interest/ic_computer_prg/ic_computer_prg.png'),
        require('@/assets/ic_interest/ic_chess/ic_chess.png'),
        require('@/assets/ic_interest/ic_cooking/ic_cooking.png'),
        require('@/assets/ic_interest/ic_dance/ic_dance.png'),
        require('@/assets/ic_interest/ic_digital_art/ic_digital_art.png'),
        require('@/assets/ic_interest/ic_darts/ic_darts.png'),
        require('@/assets/ic_interest/ic_drawing/ic_drawing.png'),
        require('@/assets/ic_interest/ic_film_making/ic_film_making.png'),
        require('@/assets/ic_interest/ic_fitness/ic_fitness.png'),
        require('@/assets/ic_interest/ic_flying/ic_flying.png'),
        require('@/assets/ic_interest/ic_gaming/ic_gaming.png'),
        require('@/assets/ic_interest/ic_gardning/ic_gardning.png'),
        require('@/assets/ic_interest/ic_guitar/ic_guitar.png'),
        require('@/assets/ic_interest/ic_investing/ic_investing.png'),
        require('@/assets/ic_interest/ic_interiordesign/ic_interiordesign.png'),
        require('@/assets/ic_interest/ic_knittng/ic_knittng.png'),
      ],
    },
  },
  {
    types: ['kinks'],
    kinks: {
      title: 'kinks?',
      singleSelection: false,
      visibility: false,
      options: [
        'Armpits',
        'Ask me',
        'BDSM',
        'Beards',
        'Bondage',
        'Chastity',
        'Cock Ball Torture',
        'Diapers',
        'Dom',
        'E-Stimulation',
        'Feet',
        'Fisting',
        'Furry',
        'Leather',
        'Muscle Worship',
        'Master',
        'Nipple',
        'Rubber',
        'S&M',
        'Slave',
        'Skinheads',
        'Socks',
        'Spit',
        'Sub',
        'Sport gear',
        'Switch',
        'Tattoos/Piercings',
        'Uniforms',
        'Used Underwear',
      ],
    },
  },
  {
    types: ['drink', 'exercise', 'marijuana', 'smoke', 'pet'],
    drink: {
      title: 'Do you drink?',
      visibility: false,
      singleSelection: true,
      options: ['Never', 'Socially', 'Frequently', 'Sober'],
    },
    exercise: {
      title: 'Do you exercise?',
      visibility: false,
      singleSelection: true,
      options: ['Active', 'Sometimes', 'Almost Never'],
    },
    marijuana: {
      title: 'Do you take marijuana?',
      visibility: false,
      singleSelection: true,
      options: ['Never', 'Sometimes', 'Regularly'],
    },
    smoke: {
      title: 'Do you smoke?',
      visibility: false,
      singleSelection: true,
      options: ['Never', 'Sometimes', 'Regularly', 'Cigars'],
    },
    pet: {
      title: 'Do you have a pet?',
      visibility: false,
      singleSelection: true,
      options: ['Don’t Want', 'None', 'Cat', 'Dog', 'Lots'],
    },
  },
  {
    types: ['language', 'zodiac_sign', 'tribes'],
    language: {
      title: 'What is your love language?',
      visibility: false,
      singleSelection: true,
      options: [
        'Word of affirmation',
        'Quality time',
        'Receiving gifts',
        'Acts of service',
        'Physical touch',
      ],
    },
    zodiac_sign: {
      title: 'What is your zodiac sign?',
      visibility: false,
      singleSelection: true,
      options: [
        'Aries',
        'Taurus',
        'Gemini',
        'Leo',
        'Cancer',
        'Virgo',
        'Libra',
        'Scorpio',
        'Sagittarius',
        'Capricorn',
        'Aquarius',
      ],
    },
    tribes: {
      title: 'What is your tribes??',
      visibility: false,
      singleSelection: true,
      options: [
        'Bear',
        'Chub',
        'Cub',
        'Daddy',
        'Discreet',
        'Gaymer',
        'Gym Bunny',
        'Leather',
        'Otter',
        'Twink',
        'Wolf',
      ],
    },
  },
  {
    types: ['personality'],
    personality: {
      title: 'What is your personality type?',
      visibility: false,
      singleSelection: true,
      options: [
        'ISTJ - The Inspector',
        'ISTP - The Crafter',
        'ISFJ - The Protector',
        'ISFJ - The Artist',
        'INFJ - The Advocate',
        'INFP - The Mediator',
        'INTJ - The Architect',
        'INTP - TheThinker',
        'ESTP - The Persuader',
        'ESTJ - The Director',
        'ESFP - The Performer',
        'ENFJ - The Giver',
        'ENFP - The Champion',
        'ENTJ - The Commander',
        'ESFJ - The Caregiver',
        'ENTP - The Debater',
      ],
    },
  },
];
