import {
  GenderIcon,
  OrientationIcon,
  EthnicityIcon,
  HeightIcon,
  WeightIcon,
  BodyTypeIcon,
  ExerciseIcon,
  DrinkingIcon,
  SmokingIcon,
  MarijuanaIcon,
  DrugsIcon,
  PetsIcon,
  KidsIcon,
  personIcon,
} from '@/assets';
export let UserList = [
  //   {
  //     id: '1',
  //     name: 'Pedro Colins',
  //     age: '26',
  //     location: 'Chicago',
  //     distance: '59mi',
  //     image: personIcon,
  //     greenTick: true,
  //     basicInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     additionalInfo: [
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //     ],
  //     spicy: [
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '2',
  //     name: 'Duglas hondo',
  //     age: '43',
  //     location: 'Miami',
  //     distance: '44mi',
  //     image: personIcon,
  //     greenTick: false,
  //     basicInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],

  //     spicy: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '3',
  //     name: 'Patrick Dumet',
  //     age: '44',
  //     location: 'Connecticut',
  //     distance: '45mi',
  //     image: personIcon,

  //     spicy: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '4',
  //     name: 'Holand Junior',
  //     age: '43',
  //     location: 'Missisippie',
  //     distance: '46mi',
  //     image: personIcon,
  //     greenTick: true,
  //     basicInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },

  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     additionalInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     spicy: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },

  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '5',
  //     name: 'Mark hanmen',
  //     age: '33',
  //     location: 'Toranto',
  //     distance: '32mi',
  //     image: personIcon,
  //     basicInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },

  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     additionalInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '6',
  //     name: 'Eric Gomez',
  //     age: '24',
  //     location: 'New york',
  //     distance: '5mi',
  //     image: personIcon,
  //     greenTick: true,
  //     additionalInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     spicy: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '7',
  //     name: 'Pedro Colins',
  //     age: '26',
  //     location: 'Chicago',
  //     distance: '59mi',
  //     image: personIcon,
  //     greenTick: true,
  //     basicInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     additionalInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     spicy: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '8',
  //     name: 'Duglas hondo',
  //     age: '43',
  //     location: 'Miami',
  //     distance: '44mi',
  //     image: personIcon,
  //     greenTick: false,
  //     basicInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],

  //     spicy: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '9',
  //     name: 'Patrick Dumet',
  //     age: '44',
  //     location: 'Connecticut',
  //     distance: '45mi',
  //     image: personIcon,

  //     spicy: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '10',
  //     name: 'Holand Junior',
  //     age: '43',
  //     location: 'Missisippie',
  //     distance: '46mi',
  //     image: personIcon,
  //     greenTick: true,
  //     basicInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },

  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     additionalInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     spicy: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },

  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '11',
  //     name: 'Mark hanmen',
  //     age: '33',
  //     location: 'Toranto',
  //     distance: '32mi',
  //     image: personIcon,
  //     basicInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },

  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     additionalInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
  //   {
  //     id: '12',
  //     name: 'Eric Gomez',
  //     age: '24',
  //     location: 'New york',
  //     distance: '5mi',
  //     image: personIcon,
  //     greenTick: true,
  //     additionalInfo: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //     spicy: [
  //       { Gender: 'Man', Icon: GenderIcon },
  //       { SexualOrientation: 'Gay', Icon: OrientationIcon },
  //       { Ethnicity: 'Pacific Islander', Icon: EthnicityIcon },
  //       { Height: '5’10”', Icon: HeightIcon },
  //       { Weight: '90lbs', Icon: WeightIcon },
  //       { BodyType: 'Stocky', Icon: BodyTypeIcon },
  //       { Exercise: 'Stocky', Icon: ExerciseIcon },
  //       { Drinking: 'Socially', Icon: DrinkingIcon },
  //       { Smoking: 'Sometimes', Icon: SmokingIcon },
  //       { Marijuana: 'Sometimes', Icon: MarijuanaIcon },
  //       { Drugs: 'Never', Icon: DrugsIcon },
  //       { Pets: 'Cats', Icon: PetsIcon },
  //       { Kids: 'Undecided', Icon: KidsIcon },
  //     ],
  //   },
];
